sonar.projectKey=HMS_REACT
sonar.projectName=HMS_REACT
sonar.projectVersion=1.0

sonar.sources=src
sonar.language=js
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=node_modules/**,test/**

# Coverage
sonar.coverage.exclusions=**

# Server
sonar.host.url=http://localhost:9000
sonar.login=sqp_0d69bcda9e399918cea73d8738a19ccd7e3a8018
