sonar.projectKey=HMS-MOBILE_SPRINT_3
sonar.projectName=HMS-MOBILE_SPRINT_3
sonar.projectVersion=1.0

sonar.sources=src
sonar.language=js
sonar.sourceEncoding=UTF-8

# Exclusions
sonar.exclusions=node_modules/**,test/**

# Coverage
sonar.coverage.exclusions=**

# Server
sonar.host.url=http://localhost:9000
sonar.login= 